# Generated by Django 3.2 on 2021-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20210415_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email_id', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
