# Generated by Django 3.2 on 2021-04-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
