# Generated by Django 3.2 on 2021-04-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email_id', models.CharField(max_length=264)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.book')),
            ],
        ),
    ]
