# Generated by Django 3.2 on 2021-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Accepted',
            field=models.BooleanField(default=False),
        ),
    ]
