# Generated by Django 3.2 on 2021-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_remove_request_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mybooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('book', models.CharField(max_length=264)),
                ('due', models.CharField(max_length=264)),
            ],
        ),
    ]
