# Generated by Django 3.2 on 2021-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_mybooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('book', models.CharField(max_length=264)),
                ('renewal_time', models.CharField(max_length=264)),
            ],
        ),
    ]
