# Generated by Django 3.2 on 2021-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_renewalrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequests',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
