# Generated by Django 3.2 on 2021-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_renewalrequests_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
