# Generated by Django 3.2 on 2021-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0011_request_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='due',
            field=models.CharField(default='10 days', max_length=200),
        ),
        migrations.AlterField(
            model_name='mybooks',
            name='due',
            field=models.CharField(default='10 days', max_length=264),
        ),
    ]
