# Generated by Django 3.2 on 2021-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0012_auto_20210417_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequests',
            name='due',
            field=models.CharField(default='10 days', max_length=200),
        ),
    ]
