# Generated by Django 3.2 on 2021-04-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0013_renewalrequests_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalrequests',
            name='due',
        ),
    ]
