# Generated by Django 3.2 on 2021-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0014_remove_renewalrequests_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
