# Generated by Django 3.2 on 2021-04-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0016_auto_20210417_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('book', models.CharField(max_length=264)),
                ('comments', models.CharField(max_length=3000)),
                ('start', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='mybooks',
            name='name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='renewalrequests',
            name='book',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='renewalrequests',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
