# Generated by Django 3.2 on 2021-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0018_auto_20210418_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='stars',
            field=models.IntegerField(default=1, max_length=6),
        ),
    ]
