# Generated by Django 3.2 on 2021-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0019_alter_ratings_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
