# Generated by Django 3.2 on 2021-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0020_alter_ratings_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('warning', models.TextField(max_length=3000)),
            ],
        ),
    ]
