# Generated by Django 3.2 on 2021-04-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0022_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author1', to='secondapp.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre1', to='secondapp.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher1', to='secondapp.book')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary1', to='secondapp.book')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='secondapp.book')),
            ],
        ),
    ]
