# Generated by Django 3.2 on 2021-04-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0023_newarrivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivals',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='summary',
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='Author',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='Genre',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='Publisher',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='Summary',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.book'),
        ),
    ]
