# Generated by Django 3.2 on 2021-04-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0024_auto_20210418_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='newarrivals',
            old_name='Summary',
            new_name='summary',
        ),
    ]
